SELECT * FROM HEART
CREATE TABLE EXP(ID INT)
ALTER TABLE HEART DROP COLUMN ID
 ALTER TABLE HEART ADD id INT
DECLARE @i INT =1,@COUNT INT
SELECT @COUNT = COUNT(*) FROM HEART

WHILE @i <= @COUNT
BEGIN
INSERT INTO EXP(id) VALUES(@i) 
SET @i = @i + 1
END
SELECT * FROM EXP