CREATE DATABASE COMPANY
USE COMPANY

CREATE TABLE EMPLOYEE (FNAME VARCHAR(40),MINIT CHAR(2), LNAME VARCHAR(40), SSN INT PRIMARY KEY , BDATE VARCHAR(40), ADDRESS VARCHAR(40), SEX VARCHAR(10),SALARY INT
,SUPER_SNN INT ,DNO INT)

CREATE TABLE DEPARTMENT (DNAME VARCHAR(40), DNUMBER INT PRIMARY KEY, MGR_SSN INT, MGR_START_DATE VARCHAR(40))

CREATE TABLE DEPT_LOCATIONS(DNUMBER INT , DLOCATION VARCHAR(40))

CREATE TABLE PROJECT(PNAME VARCHAR(40), PNUMBER VARCHAR(40) PRIMARY KEY, PLOCATION VARCHAR(40), DNUM INT )

CREATE TABLE WORKS_ON (ESSN INT, PNO VARCHAR(40), HRS VARCHAR(5))

CREATE TABLE DEPENDENT(ESSN INT , DEPENDENT_NAME VARCHAR(40),SEX VARCHAR(10), BDATE VARCHAR(40),RELATIONSHIP VARCHAR(40))

ALTER TABLE DEPT_LOCATIONS ADD FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (SUPER_SNN) REFERENCES EMPLOYEE(SSN)
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER)
ALTER TABLE DEPARTMENT ADD FOREIGN KEY (MGR_SSN) REFERENCES EMPLOYEE(SSN)
ALTER TABLE WORKS_ON ADD FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN)
ALTER TABLE DEPENDENT ADD FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN)
ALTER TABLE WORKS_ON ADD FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER)
ALTER TABLE PROJECT ADD FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER)
